# https://github.com/sbiermann/rpi-influxdb
# https://hub.docker.com/r/fg2it/grafana-armhf/
version: '2'
services:
  influxdb:
    image: sbiermann/rpi-influxdb
    container_name: influxdb
    ports:
      - "0.0.0.0:8086:8086"
      - "0.0.0.0:8083:8083" 
    volumes:
      - ~/docker/data/influxdb:/data
    links:
      - grafana
  grafana:
    image: fg2it/grafana-armhf:v3.1.1
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ~/docker/data/grafana/lib:/var/lib/grafana
      - ~/docker/data/grafana/log:/var/log/grafana
